# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "Sala de Teste",
    "description": "Esta é uma sala de teste para verificar o funcionamento do sistema."
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/e1d20120-929d-4858-b836-523668703357/questions
Content-Type: application/json

{
    "question": "O que é React e qual sua causa na natureza?"
}